apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-servicemonitor
  labels:
    release: prometheus
    namespace: monitoring 
spec:
  selector:
    matchLabels:
      app: auth
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
