apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  PLACEHOLDER: "NONE"
type: Opaque
stringData:
  GMAIL_ADDRESS: "kokuzzali909@gmail.com"
  GMAIL_PASSWORD: "4L402/@3bnRu:4dM6"